#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-reap
Version  : 9.4.0
Release  : 3
URL      : https://rubygems.org/downloads/reap-9.4.0.gem
Source0  : https://rubygems.org/downloads/reap-9.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: rubygem-reap-bin
BuildRequires : ruby
BuildRequires : rubygem-facets
BuildRequires : rubygem-rdoc
Patch1: 0001-Remove-dirs-in-gemspec.patch

%description
= Reap
== Introduction
Reap is a Ruby-based project assistant application.
Reap provides a collection of tools to help developers
prepare and release Ruby projects.

%package bin
Summary: bin components for the rubygem-reap package.
Group: Binaries

%description bin
bin components for the rubygem-reap package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n reap-9.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-reap.gemspec
%patch1 -p1

%build
gem build rubygem-reap.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
reap-9.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/reap-9.4.0
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/reap-9.4.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/MANIFEST
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/NOTES
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/README
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-announce
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-check-load
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-check-syntax
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-clean
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-clobber
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-doc
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-doc-rdoc
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-doc-ri
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-doc-spec
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-init
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-inspect
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-install
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-install-gem
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-log
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-log-changes
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-log-notes
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-make
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-make-clean
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-make-distclean
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-make-extconf
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-make-static
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-package
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-package-gem
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-package-tgz
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-package-zip
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-prepare
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-publish
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-release
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-rollout
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-scaffold
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-scm-branch
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-scm-tag
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-spec
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-stats
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-test
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-test-cross
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-test-load
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-test-solo
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-uninstall
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-uninstall-gem
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/bin/reap-version
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/test/case/test_init.rb
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/test/case/test_scaffold.rb
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/test/data/scaffold/meta/project.yaml
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/test/lib/case_testable.rb
/usr/lib64/ruby/gems/2.3.0/gems/reap-9.4.0/test/unit/lib/reap/extensions/test_array.rb
/usr/lib64/ruby/gems/2.3.0/specifications/reap-9.4.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/reap-announce
/usr/bin/reap-check-load
/usr/bin/reap-check-syntax
/usr/bin/reap-clean
/usr/bin/reap-clobber
/usr/bin/reap-doc
/usr/bin/reap-doc-rdoc
/usr/bin/reap-doc-ri
/usr/bin/reap-doc-spec
/usr/bin/reap-init
/usr/bin/reap-inspect
/usr/bin/reap-install
/usr/bin/reap-install-gem
/usr/bin/reap-log
/usr/bin/reap-log-changes
/usr/bin/reap-log-notes
/usr/bin/reap-make
/usr/bin/reap-make-clean
/usr/bin/reap-make-distclean
/usr/bin/reap-make-extconf
/usr/bin/reap-make-static
/usr/bin/reap-package
/usr/bin/reap-package-gem
/usr/bin/reap-package-tgz
/usr/bin/reap-package-zip
/usr/bin/reap-prepare
/usr/bin/reap-publish
/usr/bin/reap-release
/usr/bin/reap-rollout
/usr/bin/reap-scaffold
/usr/bin/reap-scm-branch
/usr/bin/reap-scm-tag
/usr/bin/reap-spec
/usr/bin/reap-stats
/usr/bin/reap-test
/usr/bin/reap-test-cross
/usr/bin/reap-test-load
/usr/bin/reap-test-solo
/usr/bin/reap-uninstall
/usr/bin/reap-uninstall-gem
/usr/bin/reap-version
